import asyncio
from asyncio import Task
from dataclasses import dataclass, replace
from uuid import UUID

from ask.messages import MessageTree
from ask.models import Message, Text, Command
from ask.shells import PYTHON_SHELL
from ask.tools import ToolCallStatus

COMMAND_CAVEAT_MESSAGE = (
    "Caveat: The messages below were generated by the user while running local commands. "
    "DO NOT respond to these messages or otherwise consider them in your response unless the user explicitly asks you to.")

@dataclass
class PythonCommand(Command):
    output: str = ''
    error: str = ''
    status: ToolCallStatus = ToolCallStatus.PENDING

    @classmethod
    async def run(cls, value: str, messages: MessageTree, uuid: UUID, command: 'PythonCommand') -> None:
        try:
            nodes = PYTHON_SHELL.parse(value)
            output, exception = await PYTHON_SHELL.execute(nodes=nodes, timeout_seconds=10)
            status = ToolCallStatus.FAILED if exception else ToolCallStatus.COMPLETED
            messages.update(uuid, replace(command, output=output, error=exception, status=status))
        except asyncio.CancelledError:
            messages.update(uuid, replace(command, status=ToolCallStatus.CANCELLED))

    @classmethod
    def create(cls, value: str, messages: MessageTree, head: UUID | None) -> tuple[UUID, list[Task]]:
        command = PythonCommand(command=value)
        head = messages.add('user', head, command)
        task = asyncio.create_task(cls.run(value, messages, head, command))
        return head, [task]

    def messages(self) -> list[Message]:
        if self.status is ToolCallStatus.CANCELLED:
            output = "[Request interrupted by user]"
        else:
            output = f"<python-stdout>\n{self.output}\n</python-stdout>\n<python-stderr>\n{self.error}\n</python-stderr>"
        return [
            Message(role='user', content=Text(COMMAND_CAVEAT_MESSAGE)),
            Message(role='user', content=Text(f"<python-code>{self.command}</python-code>")),
            Message(role='user', content=Text(output))]
