prompt = """
Lists files and directories in a given path.
- The path parameter must be an absolute path, not a relative path.
- You can optionally provide an array of glob patterns to ignore with the ignore parameter.
- You should generally prefer the Glob and Grep tools, if you know which directories to search.
"""