prompt = """
Executes a given python command in a persistent python REPL with optional timeout, ensuring proper handling and security measures.

Usage notes:
  - The code argument is required.
  - You can specify an optional timeout in milliseconds (up to 600000ms / 10 minutes). If not specified, commands will timeout after 120000ms (2 minutes).
  - It is very helpful if you write a clear, concise description of what this command does in 5-10 words.
  - If the output exceeds 30000 characters, output will be truncated before being returned to you.
  - The REPL state will persist across calls. This means that anything you import and any variables you define will still be set for future calls, so you don't need to set them again. If you want to reset the REPL state, run `exit()` and the REPL will be restarted automatically.
"""